### ISSUE TITLE
Load images to Projects 

### ISSUE THREAD

**Issue by stacykutyepov** [surudhb/gatsby-personal-site-template#2]
Hello! I really like your template, and I have decided to use it for my portfolio website!
I just can't figure out how to add images to projects.

For each project I have created a separate folder where I've put image.png and file.md
What do I do wrong?

<img width="240" alt="Screen Shot 2020-08-12 at 11 43 50 AM" src="https://user-images.githubusercontent.com/62475313/90036488-193cb900-dc91-11ea-91fc-85e2b32b63a9.png">

**Comment by surudhb** [comment]
Hi Stacy! Glad to hear you like the template!

I think I see what might be the issue. The file names for "feature" photos for projects should be `feature.png`.
You can change that to anything you like [here](https://github.com/surudhb/gatsby-personal-site-template/blob/master/src/pages/projects.js#L61-L78).

Right now, for each project, the query finds any images containing the words `feature` with the extension `png`.
And in [`projects.js`](https://github.com/surudhb/gatsby-personal-site-template/blob/master/src/pages/projects.js#L11), the `getImageMap` function limits the number of photos to display by default to 3.

Lmk if that resolved the issue,
Surudh

**Comment by stacykutyepov** [comment]
Yes, it works! Thank you so much!
