### ISSUE TITLE
npm vulnerabilities

### ISSUE THREAD

**Issue by nappernick** [surudhb/gatsby-personal-site-template#4]
Cloned this repo & found an insane number of vulnerabilities - 897, 38 of which were "high". Any explanation for this? I npm audit fixed, and most were repairable, but 18 vulnerabilities required manual review. Excited by the template, worried by the incredible number of vulnerabilities.

**Comment by surudhb** [comment]
Hey there! Thanks for checking out the template. You are welcome to browse the list of packages used in the project in `package.json` so I don't think security should be an issue anywhere as all packages used in the template are industry standard and well supported. The vulnerabilities you see are an indication of that support. As things get deprecated/replace/optimized in those packages, some of these changes will be reflected in updates and some through vulnerabilities requiring npm to ask you whether you wish to stick with the older version or not and usually updating the package is the better option. I think you should be fine as long as you run `npm update`
