### ISSUE TITLE
Server Side Rendering - Dark Mode Default

### ISSUE THREAD

**Issue by SakshamInABox** [surudhb/gatsby-personal-site-template#5]
Hi there,

In utils/theme.js, I have replaced the following lines as shown below:

Original
```
const defaultState = {
  dark: false,
  toString: () => `light`,
  toggleDark: () => {},
}

const ThemeContext = React.createContext(defaultState)

class ThemeProvider extends Component {
  state = {
    dark: false,
  }
```

Replaced:
```
const defaultState = {
  dark: true,
  toString: () => `dark`,
  toggleDark: () => {},
}

const ThemeContext = React.createContext(defaultState)

class ThemeProvider extends Component {
  state = {
    dark: true,
  }
  ```
  
 This is setting Dark mode as default correctly when Gatsby develop environment is used. However, when server side rendering takes place or via gatsby build -> gatsby serve, it defaults to white theme, instead of dark. Do you know why this might be happening?

**Comment by surudhb** [comment]
Hi, I think this definitely might have to do with `theme-light` being leftover somewhere in the app. Possibly in the root div. I think removing that should resolve the issue.

EDIT: Found the culprit! https://github.com/surudhb/gatsby-personal-site-template/blob/master/src/components/PageLayout.js#L7

**Comment by SakshamInABox** [comment]
Thanks for that. Unfortunately, looks like that's not it. I have a preview branch here with theme-light removed as a class from PageLayout file and no other theme-light present in the code https://08657a54.sakshamanand.pages.dev/ . I will continue poking around, see if I find something else that may be causing this.

Edit: I noticed your site also had the issue where icons go really large on page load and then return to normal after a second or two. This is happening because of FontAwesome CSS being injected post load. I was able to fix this by adding "width="0" as a parameter for all `<FontAwesomeIcon>` entries in /src/pages/index.js.

**Comment by SakshamInABox** [comment]
After a few hours of researching and a couple of cups of coffee, found a (now obvious) fix. The JavaScript was being injected post render, which is why the page was not reflecting the updated state of the theme. The following steps fixed it for me:

Steps:
1) In the root folder for this template, create a file called gatsby-ssr.js.
2) Copy paste content of gatsby-browser.js into gatsby-ssr.js

Note: You can also add the following flag to gatsby-config.js to replicate SSR environment locally:
```
flags: {
  DEV_SSR: true,
},
```
